# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import query_pb2 as query__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='task.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntask.proto\x1a\x0bquery.proto\"\x8a\x01\n\tProtoTask\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x0c\n\x04mode\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x62_name\x18\x04 \x01(\t\x12\x12\n\nnlq_tokens\x18\x05 \x03(\t\x12\t\n\x01n\x18\x06 \x01(\x05\x12\x11\n\ttsq_level\x18\x08 \x01(\t\x12\x0f\n\x07timeout\x18\t \x01(\x05\"+\n\x0fProtoCandidates\x12\x18\n\x03\x63qs\x18\x01 \x03(\x0b\x32\x0b.ProtoQueryb\x06proto3')
  ,
  dependencies=[query__pb2.DESCRIPTOR,])




_PROTOTASK = _descriptor.Descriptor(
  name='ProtoTask',
  full_name='ProtoTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ProtoTask.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='ProtoTask.dataset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='ProtoTask.mode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='db_name', full_name='ProtoTask.db_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nlq_tokens', full_name='ProtoTask.nlq_tokens', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n', full_name='ProtoTask.n', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tsq_level', full_name='ProtoTask.tsq_level', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='ProtoTask.timeout', index=7,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=166,
)


_PROTOCANDIDATES = _descriptor.Descriptor(
  name='ProtoCandidates',
  full_name='ProtoCandidates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cqs', full_name='ProtoCandidates.cqs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=211,
)

_PROTOCANDIDATES.fields_by_name['cqs'].message_type = query__pb2._PROTOQUERY
DESCRIPTOR.message_types_by_name['ProtoTask'] = _PROTOTASK
DESCRIPTOR.message_types_by_name['ProtoCandidates'] = _PROTOCANDIDATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoTask = _reflection.GeneratedProtocolMessageType('ProtoTask', (_message.Message,), dict(
  DESCRIPTOR = _PROTOTASK,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:ProtoTask)
  ))
_sym_db.RegisterMessage(ProtoTask)

ProtoCandidates = _reflection.GeneratedProtocolMessageType('ProtoCandidates', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCANDIDATES,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:ProtoCandidates)
  ))
_sym_db.RegisterMessage(ProtoCandidates)


# @@protoc_insertion_point(module_scope)
